# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeploymentTest@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
    subscriptionId: 'c00d16c7-6c1f-4c03-9be1-6934a4c49682'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'abrg'
    location: 'Australia Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://testforpat.blob.core.windows.net/publicdata/template.json'
    csmParametersFileLink: 'https://testforpat.blob.core.windows.net/publicdata/parameters.json'
    deploymentMode: 'Incremental'