stages:
  - stage: Stage1
    jobs:
      - deployment: DeployLatest
        environment: test
      - job: UpdateChangeRequest
        steps:
          - task: UpdateServiceNowChangeRequest@2
            displayName: 'Update ServiceNow Change Request'
            inputs:
              ServiceNowConnection: 'ServicenowConnection'
              NewStatus: 'Assess'
              WorkNotes: 'sample notes'
              ChangeRequestNumber: ''
              otherParameters: '{"u_hello":"hello"}'
pool: server