stages:
  - stage: Stage1
    jobs:
      - deployment: DeployLatest
        environment: test
      - job: UpdateChangeRequest
        steps:
          - task: UpdateServiceNowChangeRequest@2
            displayName: 'Close ServiceNow change [Successfull]'
            inputs:
              ServiceNowConnection: 'ServicenowConnection'
              NewStatus: 7
              WorkNotes: 'sample notes'
              otherParameters: '{"u_close_notes": "succeeded" }'
pool: server